"""Cross-design summary table: focus + collection for every lens in designs/.

    python scripts/summarize_designs.py

Reads each design's metalens_layout_*.npz and lens_scale_*.hdf5, recomputes the Phase-2
focus metrics and Phase-3 reciprocity collection (identical math to the per-design scripts),
and prints a markdown table on stdout. Comparison figures are produced separately by
scripts/make_comparison_figures.py.

Designs whose FDTD result is not present are listed as pending and skipped, so this runs
free at any time. No cloud cost.
"""
from pathlib import Path

import numpy as np
import tidy3d as td

ROOT = Path(__file__).resolve().parents[1]
DESIGNS = ROOT / "designs"
Z0 = 376.730313668


def analyze(folder):
    lay_files = list(folder.glob("data/metalens_layout_*.npz"))
    if not lay_files:
        return None
    lay = np.load(lay_files[0], allow_pickle=True)
    tag = lay_files[0].stem.replace("metalens_layout_", "")
    hdf5 = folder / "data" / f"lens_scale_{tag}.hdf5"
    lda0 = float(lay["wavelength_um"]); D = float(lay["aperture_um"])
    f_work = float(lay["working_distance_um"]); NA = float(lay["NA"])
    n_mode = float(lay["n_SiO2"]); amp = np.asarray(lay["amplitude"], float)
    label = str(lay["material"])
    row = dict(label=label, D=D, NA=NA, N=amp.size,
               span=float(lay["library_span_x2pi"]) if "library_span_x2pi" in lay.files else 1.06,
               pending=not hdf5.exists())
    if row["pending"]:
        return row

    freq0 = td.C_0 / lda0
    k = 2 * np.pi / (lda0 * 1e-6)
    A_ap = np.pi * ((D / 2) * 1e-6) ** 2
    sd = td.SimulationData.from_file(str(hdf5))

    proj = sd["focal_plane_proj"].fields_cartesian
    zc = float(proj.z.values[0])
    Efx, Efy, Efz = (complex(proj[c].sel(f=freq0, z=zc).interp(x=0.0, y=0.0).values)
                     for c in ("Ex", "Ey", "Ez"))
    band = sd["xz"].Ex.sel(f=freq0).sel(x=slice(-D / 2, D / 2), z=slice(-0.55, -0.03))
    R_pow = max(0.0, 1.0 - float(np.mean(amp ** 2)))
    E_inc = np.sqrt(np.mean(np.abs(band.values) ** 2) / (1.0 + R_pow))

    pref = (3 * np.pi) / (2 * k ** 2 * n_mode * A_ap)
    E_xmode = np.array([Efx, Efy, Efz]); E_ymode = np.array([-Efy, Efx, Efz])
    dip = {"pi": np.array([1.0, 0.0, 0.0]),
           "sigma": np.array([0.0, 1.0, 1j]) / np.sqrt(2)}
    into = lambda mE, ph: pref * abs(np.vdot(ph, mE)) ** 2 / E_inc ** 2
    eta_pi = into(E_xmode, dip["pi"]) + into(E_ymode, dip["pi"])
    eta_sig = into(E_xmode, dip["sigma"]) + into(E_ymode, dip["sigma"])
    c = np.cos(np.arcsin(NA))
    eta_unpol = (eta_pi + 2 * eta_sig) / 3   # orientation average over pi, sigma+, sigma-

    # focus metrics
    Ex = proj["Ex"].sel(f=freq0, z=zc).values
    I = np.abs(Ex) ** 2 + np.abs(proj["Ey"].sel(f=freq0, z=zc).values) ** 2 \
        + np.abs(proj["Ez"].sel(f=freq0, z=zc).values) ** 2
    xs = proj.x.values; ipk, jpk = np.unravel_index(np.argmax(I), I.shape)

    def fwhm(coord, prof):
        prof = prof / prof.max(); a = np.where(prof >= 0.5)[0]
        if a.size < 2:
            return np.nan
        lo, hi = a[0], a[-1]
        left = np.interp(0.5, [prof[max(lo - 1, 0)], prof[lo]], [coord[max(lo - 1, 0)], coord[lo]])
        right = np.interp(0.5, [prof[min(hi + 1, len(coord) - 1)], prof[hi]],
                          [coord[min(hi + 1, len(coord) - 1)], coord[hi]])
        return abs(right - left)

    enh = np.sqrt(abs(Efx) ** 2 + abs(Efy) ** 2 + abs(Efz) ** 2) / E_inc
    row.update(eta_pi=eta_pi, eta_sig=eta_sig, eta_unpol=eta_unpol,
               eta_geom=(1 - c) / 2, enh=enh,
               fwhm=np.nanmean([fwhm(xs, I[:, jpk]), fwhm(proj.y.values, I[ipk, :])]),
               dl=0.514 * lda0 / NA)
    return row


folders = sorted(p for p in DESIGNS.iterdir() if p.is_dir())
rows = [r for r in (analyze(f) for f in folders) if r]
done = [r for r in rows if not r["pending"]]
pending = [r for r in rows if r["pending"]]

print("\n| design | NA | cylinders | span (x2pi) | FWHM/limit | enh | "
      "eta_pi (%) | sigma+/- both (%) | unpol (%) | eta_geom (%) |")
print("|---|---|---|---|---|---|---|---|---|---|")
for r in sorted(done, key=lambda r: (r["label"], r["D"])):
    print(f"| {r['label']} D={r['D']:.0f}µm | {r['NA']:.3f} | {r['N']} | {r['span']:.2f} | "
          f"{r['fwhm']:.2f}/{r['dl']:.2f} | {r['enh']:.1f}× | {r['eta_pi']*100:.3f} | "
          f"{r['eta_sig']*100:.3f} | {r['eta_unpol']*100:.3f} | {r['eta_geom']*100:.2f} |")
for r in pending:
    print(f"| {r['label']} D={r['D']:.0f}µm | {r['NA']:.3f} | {r['N']} | {r['span']:.2f} | "
          f"- | - | pending FDTD | | | {(1-np.cos(np.arcsin(r['NA'])))/2*100:.2f} |")

if pending:
    print(f"\npending FDTD ({len(pending)}): " + ", ".join(f"{r['label']} D={r['D']:.0f}µm" for r in pending))
print("\nComparison figures are generated by scripts/make_comparison_figures.py.")
